Refactor to typescript
game-ci/unity-test-runner pull request #158
Opened 2022-01-09 14:35 UTC by davidmfinol

#### Changes

- Refactor to typescript

#### Checklist

- [x] Read the contribution [guide](../CONTRIBUTING.md) and accept the [code](../CODE_OF_CONDUCT.md) of conduct
- [x] Readme (updated or not needed)
- [x] Tests (added, updated or not needed)

2022-01-09 23:46 UTC, GabLeRoux reviewed
I assume it's normal to have the `dist` folder tracked (for example, unity-builder does the same). Just asking to make sure it's normal to have that many changed lines: `+24,769 −3,191`.

2022-01-09 23:49 UTC, GabLeRoux approved these changes
I'm seeing some duplicated code between repositories. I'm wondering how we could solve this, but again, this should most likely be solved later. Thanks for converting this to typescript :tada: :shipit:

2022-01-10 00:15 UTC, davidmfinol commented
Yep, I basically copy-pasted a lot of code between `unity-request-activation-file`, `unity-activate`, `unity-test-runner`, and `unity-builder`.
I agree that there should be a way to have a single repo (in `unity-actions`?) that hosts that shared code, but I think that change can be made after all the actions are already using a very similar code base.

2022-01-10 13:38 UTC, webbertakken requested changes
we need to upgrade to v1 of docker images and decide whether we want to keep a rolling tag (like we do now with v0) or lock it to minor level of the version.

2022-01-11 03:40 UTC, davidmfinol commented on .husky/pre-commit
>  npx lint-staged
Updated

2022-01-11 03:45 UTC, davidmfinol commented
> we need to upgrade to v1 of docker images and decide whether we want to keep a rolling tag (like we do now with v0) or lock it to minor level of the version.

@webbertakken Moving to v1 of docker images will be done in a follow-up, right? Is it ok to merge this PR now?

2022-01-11 04:30 UTC, GabLeRoux commented
> > we need to upgrade to v1 of docker images and decide whether we want to keep a rolling tag (like we do now with v0) or lock it to minor level of the version.
> 
> @webbertakken Moving to v1 of docker images will be done in a follow-up, right? Is it ok to merge this PR now?

I tend to say yes but I’m unsure of the implications  and would prefer @webbertakken ’s input on this

2022-01-11 11:07 UTC, webbertakken commented
Yes, but just know that the version field in package.json will not be auto-updated (as it's not a public npm package) so setting it to v2.0.0 might be confusing.

![image](https://user-images.githubusercontent.com/20756439/148931783-59b2a895-1a48-4ac5-8eba-b99f30b98382.png)

On the other hand 🤷‍♂️

2022-01-11 11:08 UTC, webbertakken approved these changes

2022-01-11 11:52 UTC, merged