perf: avoid creating temporary docker image
game-ci/unity-test-runner pull request #177
Opened 2022-03-30 18:45 UTC by paulpach

when running the tests,  we create a brand new docker image with all the scripts inside.

This POC changes the approach to just mount the scripts as a volume.  In my self hosted runner this is significantly reducing the time it takes to test my app
Before:
<img width="977" alt="Screen Shot 2022-03-30 at 1 43 02 PM" src="https://user-images.githubusercontent.com/466007/160908325-476c7aa1-0873-4087-881f-dea689a1bbc0.png">
After:
<img width="964" alt="Screen Shot 2022-03-30 at 1 43 47 PM" src="https://user-images.githubusercontent.com/466007/160908360-520f7be2-e8f2-43e7-b1b5-242bc048b5db.png">

#### Changes

- ...

#### Checklist

- [x] Read the contribution [guide](../CONTRIBUTING.md) and accept the [code](../CODE_OF_CONDUCT.md) of conduct
- [ ] Readme (updated or not needed)
- [ ] Tests (added, updated or not needed)

2022-03-30 19:21 UTC, paulpach commented on src/model/docker.ts
> +        --
```suggestion
        -- \
```

2022-03-30 20:41 UTC, webbertakken commented on src/model/docker.ts
> +        /usr/bin/bash /entrypoint.sh` ;
[](https://user-images.githubusercontent.com/20756439/160925541-594be8b0-b8f4-48ac-9903-855209de796b.png)I believe you don't need to pass the -- in this case, that's only necessary in k8s when passing something to the API and then passing an argument to the resulting resource.

In this case we're running a command in the docker image directly. So we can do the command part without the double hyphens

![image](https://user-images.githubusercontent.com/20756439/160927131-521c73e9-cfaf-43c0-abea-d40c9e9af40b.png)

```suggestion
        ${image} \
        /usr/bin/bash /entrypoint.sh` ;
```

2022-03-30 20:42 UTC, webbertakken requested changes
Amazing performance fix! Thank you.

Looks mostly good!

2022-04-02 16:20 UTC, webbertakken approved these changes

2022-04-03 03:47 UTC, paulpach commented on src/index.ts
>        // Build docker image
```suggestion
```

2022-04-03 10:03 UTC, webbertakken commented on src/index.ts
>        // Run docker image
```suggestion
```

2022-04-03 10:14 UTC, merged

2022-04-03 10:15 UTC, webbertakken commented
Thank you very much for this nice performance improvement!